---

- hosts: all
  become: true
  tasks:

  - name: install apache, php packages and update repo for Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu" 

  - name: install apache, php packages and update repo for CentOS
    yum:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS" 
